=== ObolNetwork/obol-sdk/spec/schemas/cluster.lock.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ObolNetwork/obol-sdk/spec/schemas/cluster.lock.json",
  "title": "cluster.lock",
  "properties": {
    "cluster_definition": {
      "properties": {
        "compounding": {
          "type": "boolean"
        },
        "config_hash": {
          "type": "string"
        },
        "consensus_protocol": {
          "type": "string"
        },
        "creator": {
          "properties": {
            "address": {
              "type": "string"
            },
            "config_signature": {
              "type": "string"
            }
          },
          "required": [
            "address"
          ],
          "type": "object"
        },
        "definition_hash": {
          "type": "string"
        },
        "deposit_amounts": {
          "anyOf": [
            {
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "minimum": 0,
                    "type": "integer"
                  }
                ]
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "dkg_algorithm": {
          "type": "string"
        },
        "fork_version": {
          "description": "fork version (4 bytes)",
          "pattern": "^0x[0-9a-fA-F]{8}$",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "num_validators": {
          "minimum": 0,
          "type": "integer"
        },
        "operators": {
          "anyOf": [
            {
              "items": {
                "properties": {
                  "address": {
                    "type": "string"
                  },
                  "config_signature": {
                    "type": "string"
                  },
                  "enr": {
                    "type": "string"
                  },
                  "enr_signature": {
                    "type": "string"
                  }
                },
                "type": "object"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "target_gas_limit": {
          "minimum": 0,
          "type": "integer"
        },
        "threshold": {
          "minimum": 0,
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        },
        "uuid": {
          "type": "string"
        },
        "validators": {
          "anyOf": [
            {
              "items": {
                "properties": {
                  "fee_recipient_address": {
                    "type": "string"
                  },
                  "withdrawal_address": {
                    "type": "string"
                  }
                },
                "required": [
                  "fee_recipient_address",
                  "withdrawal_address"
                ],
                "type": "object"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "version",
        "num_validators",
        "threshold",
        "fork_version",
        "config_hash",
        "creator",
        "operators",
        "validators"
      ],
      "type": "object"
    },
    "distributed_validators": {
      "items": {
        "properties": {
          "builder_registration": {
            "properties": {
              "message": {
                "properties": {
                  "fee_recipient": {
                    "type": "string"
                  },
                  "gas_limit": {
                    "minimum": 0,
                    "type": "integer"
                  },
                  "pubkey": {
                    "type": "string"
                  },
                  "timestamp": {
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "required": [
                  "fee_recipient",
                  "gas_limit",
                  "timestamp",
                  "pubkey"
                ],
                "type": "object"
              },
              "signature": {
                "type": "string"
              }
            },
            "required": [
              "message",
              "signature"
            ],
            "type": "object"
          },
          "deposit_data": {
            "properties": {
              "amount": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "minimum": 0,
                    "type": "integer"
                  }
                ]
              },
              "deposit_data_root": {
                "type": "string"
              },
              "pubkey": {
                "type": "string"
              },
              "signature": {
                "type": "string"
              },
              "withdrawal_credentials": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "distributed_public_key": {
            "type": "string"
          },
          "partial_deposit_data": {
            "anyOf": [
              {
                "items": {
                  "properties": {
                    "amount": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "minimum": 0,
                          "type": "integer"
                        }
                      ]
                    },
                    "deposit_data_root": {
                      "type": "string"
                    },
                    "pubkey": {
                      "type": "string"
                    },
                    "signature": {
                      "type": "string"
                    },
                    "withdrawal_credentials": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "type": "array"
              },
              {
                "type": "null"
              }
            ]
          },
          "public_shares": {
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "distributed_public_key",
          "public_shares"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "lock_hash": {
      "type": "string"
    },
    "node_signatures": {
      "anyOf": [
        {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ]
    },
    "signature_aggregate": {
      "type": "string"
    }
  },
  "required": [
    "cluster_definition",
    "distributed_validators",
    "signature_aggregate",
    "lock_hash"
  ],
  "type": "object"
}

=== ObolNetwork/obol-sdk/cluster-lock-with-safe.json
{
 "cluster_definition": {
  "name": "Mainnet Safe",
  "creator": {
   "address": "0x86B8145c98e5BD25BA722645b15eD65f024a87EC",
   "config_signature": "0xefd21c2312d04828e3f625222396b90cadd733a32815a66737927a3c200e859352a39cc509968a1539a5d0a3ba76e63c31e158097b7648c8ad176628057ec1971c"
  },
  "operators": [
   {
    "address": "0x86B8145c98e5BD25BA722645b15eD65f024a87EC",
    "enr": "enr:-HW4QCRE5Y94gDlShBxoe2ZKisye-mkp27v5GJWy-fvd5NszMeqL1hdKC-Wx3NDDLDrw8CBDCSvH-fTDIu7ieAUYpJWAgmlkgnY0iXNlY3AyNTZrMaECTsPdOmEF16TF-1rwcsB2NtyeRhB9PPnpQYI1MFXnsac",
    "config_signature": "0x60dad0b0ebcb5894a258a937243e4d2d87eb19df5dc5df2ffdd48c1719834ee853a59e282d527574de9865f1e886c6089877bc1bbb2f8ac851c9fa91d972e72d1b",
    "enr_signature": "0x633d69b9b916bdae52c9020b43ae816f036a1719917f00aee2cea113c2eb257a20950051a853f88179a5133d46d94451238e4915f20505b9b39af2bd464d0f4a1b"
   },
   {
    "address": "0xf6fF1a7A14D01e86a175bA958d3B6C75f2213966",
    "enr": "enr:-HW4QKJwklKw4sbM7RF6A6oyvN4f3XlmKC3gyg1Zgl6DQuHEO2mzBUn3sGWRZbNlQdNsffiiFYvaETqWNbJlzw9Fc0iAgmlkgnY0iXNlY3AyNTZrMaEDQpyNGeWosddyTPURramdKbJOrIcmEeXnN4eo6co5SzE",
    "config_signature": "0x6d26ffac0175e73ba6942b4a76825f601cfd09317f402b3f4020a29bda69a988445e20e4c1d4e82a636a4c9304fe84a8323561175685dc9b1906bb930e9499951b",
    "enr_signature": "0x10ec47ea8c77b83e40e752caec4c06e72be1824d963ca8fd66af08386c1190c569d39fce6c6b5cfbcd9367553b2269b4a0a47f598f518dbebd53c8b9bc33fddc1c"
   },
   {
    "address": "0xd501824fD822dA83d72E1e87c4b7c7392C0F16e2",
    "enr": "enr:-HW4QE9QGxw69GbB8sWv-M6azW-xGhsTGu9_sOaiAwMguuk4Kfuqe7k7pFkgZEWThi8MNOGVfh0eu5cxGfXw63V_1mSAgmlkgnY0iXNlY3AyNTZrMaEDD2ELq-_Mf85Yt5TDmyGD-ls88XIcBMjpVlWkWdxERqU",
    "config_signature": "0xfe0e5d214eff25868910cd74da79cddc8511ce2527cfe8fddbd7ec05a928715260b0d3c5415dd1a42c41a879ccde0b6a9e9238c1cb3bbc4e22409fab6a95413c1b",
    "enr_signature": "0x06f7de645045021b7483f99df2983c2f13e7e062870313f485360f97ac0db33328b919f71b2bc09b87c4eee276cf7ccc0e1a3cb5c1bd59862e3387e884001e2e1b"
   },
   {
    "address": "0x4d6c432b7E2F326B4DDf524ea9E56649e5A7C298",
    "enr": "enr:-HW4QO4tGBoddAcJjpZQokjjoU4sNe465EGs7UhFdv8gle1FNBcqoXl4lQZaBbl7dby8XvO8uVvQ0qCU5CvGCEBd53OAgmlkgnY0iXNlY3AyNTZrMaEDzrup9I6JmJbwwFqH3cTxIvhhPxMO6XbfoHmwJr6k1W8",
    "config_signature": "0xaf38ffcf5c8e90bbbae0aca2957196701b60ce321ddd702019e0f5805223b82c25f73fc11599aa7621ff364cf7ced6678cf83c16cf22518e9c990a6dcca4c35f1c",
    "enr_signature": "0x862e8d1d3980c2235ef5be2383551ebb3cb9ae8eb05035914fbb361bbbbeb91813bcc739af160f1a2e9579482ff876d1f0e62fae8c986596e0da3398b167e2511b"
   }
  ],
  "uuid": "d653dff4-fd60-4bfc-b9f8-c739d2de0ac7",
  "version": "v1.10.0",
  "timestamp": "2026-03-12T15:12:46.803Z",
  "num_validators": 2,
  "threshold": 3,
  "validators": [
   {
    "fee_recipient_address": "0x86B8145c98e5BD25BA722645b15eD65f024a87EC",
    "withdrawal_address": "0x86B8145c98e5BD25BA722645b15eD65f024a87EC"
   },
   {
    "fee_recipient_address": "0x86B8145c98e5BD25BA722645b15eD65f024a87EC",
    "withdrawal_address": "0x86B8145c98e5BD25BA722645b15eD65f024a87EC"
   }
  ],
  "dkg_algorithm": "default",
  "fork_version": "0x00000000",
  "deposit_amounts": null,
  "consensus_protocol": "",
  "target_gas_limit": 36000000,
  "compounding": true,
  "config_hash": "0xb8e999fc53176cdd292080802df23447ad34088446558bd3b1e50d7d92eab35a",
  "definition_hash": "0x9ec6c5e3203eca6a0ef96492f3f526750c8f1a369816f6abf108d2b54178660f"
 },
 "distributed_validators": [
  {
   "distributed_public_key": "0x84455a235914518c8c2b16718bd8476fc96725ce0057baf2ba4bd57ce8749073f8b207e219f8204623c66c4bdb943591",
   "public_shares": [
    "0x93207f028c76b256b96845ee7159f73707be49270738dc5730fa7aff9ffdd2db32ddbadc72e8ae9d165e9888939adfe9",
    "0xa21447fdd186e0e88fe274e829419364ec5c3b62c1e49d0acc7fa6ff725182fee41d772725e8adcc29625b22fb06a406",
    "0x8582f33fa8b545fc1f8c9fb0d94f20b39cabc2e53065ee4da0967735b7a75e0ea23371df3c1cd6f81b735060993b62b2",
    "0xb6d27b7ec2cbf74a3b23d55319136f1b417fa0361b66f440e0167e593efb618eccba38b80d90f071f346b1ab5e7b3407"
   ],
   "builder_registration": {
    "message": {
     "fee_recipient": "0x86b8145c98e5bd25ba722645b15ed65f024a87ec",
     "gas_limit": 36000000,
     "timestamp": 1606824023,
     "pubkey": "0x84455a235914518c8c2b16718bd8476fc96725ce0057baf2ba4bd57ce8749073f8b207e219f8204623c66c4bdb943591"
    },
    "signature": "0x8fdb84f1f91c08ba887e5b9fe133a4b3fe6cfbde3180c3f346a2164ec1cbbc2ba784c5301f34e308c7288347ecdb4a2917ad349a0d38f3b94a1852425938ec95d5653e2bb01cae63d7a7e36af66e278075c3d6da8b5662f0b550b04be61d65d6"
   },
   "partial_deposit_data": [
    {
     "pubkey": "0x84455a235914518c8c2b16718bd8476fc96725ce0057baf2ba4bd57ce8749073f8b207e219f8204623c66c4bdb943591",
     "withdrawal_credentials": "0x02000000000000000000000086b8145c98e5bd25ba722645b15ed65f024a87ec",
     "amount": "1000000000",
     "signature": "0xa099405ea1a16e0c0d4c52973d2ec67a749fb432a74bfbf7e742bb37e26503d14c109c1eaab191d5bfc3330d2f08bdc00033c3100fc2b3e2b0d1d9b95d1081610a64f41b6958cd674236ecc753f245519bb2b3a882ca0a064cba1b42bd461739"
    },
    {
     "pubkey": "0x84455a235914518c8c2b16718bd8476fc96725ce0057baf2ba4bd57ce8749073f8b207e219f8204623c66c4bdb943591",
     "withdrawal_credentials": "0x02000000000000000000000086b8145c98e5bd25ba722645b15ed65f024a87ec",
     "amount": "8000000000",
     "signature": "0x9968acf3b3dbef9ea33caf5863623c0c7cc8c98a5d14865e0c9dce63cb106b2020adc37bd751e70fba9000b340ea89b201033c3cfc9ee769c397373ab95288d1f9f6254afcb7c95ff39e2eaf9517bb568987a414a4f5e654591aad4927d0b38e"
    },
    {
     "pubkey": "0x84455a235914518c8c2b16718bd8476fc96725ce0057baf2ba4bd57ce8749073f8b207e219f8204623c66c4bdb943591",
     "withdrawal_credentials": "0x02000000000000000000000086b8145c98e5bd25ba722645b15ed65f024a87ec",
     "amount": "32000000000",
     "signature": "0xad6545c2dc4c685dec126b346395a2591d102941bd353baf73511c7db3d799ea13ba4dc6ac30540c245b1166cc186bd60f61a2ccceb2fe3107e52b0f725166e6a5d8801fb143af32cfaead6b844cb6ffe71d807a16c18f00fd3bcea9fcb66ee3"
    },
    {
     "pubkey": "0x84455a235914518c8c2b16718bd8476fc96725ce0057baf2ba4bd57ce8749073f8b207e219f8204623c66c4bdb943591",
     "withdrawal_credentials": "0x02000000000000000000000086b8145c98e5bd25ba722645b15ed65f024a87ec",
     "amount": "256000000000",
     "signature": "0x8675c08d8c140766de03de7f704f415f54c97c5b55bf97a2bcb403c33003233ba8dcbaa5aec44d0884bf90f7dc0ceb72004b9e484cade15612b093c0a95fb6da35fdc54678b5f785ee2fdf69fc8e33c9c512a62e1b1dbf34986072983f884111"
    }
   ]
  },
  {
   "distributed_public_key": "0x92360c8ab886fb5188e58091932b08a8dbc17c1fd3510c0e52816478d4ede55d352bdf6f5e165ee2382d7d73ab6b330b",
   "public_shares": [
    "0x91c8c2b02aa1176a00b7f29a2f4e500be8cd766dff7bf976007b5918b3819725b96818b6a284331a8d649e3d8ccc158b",
    "0x981c071fb49a8e99b3bc73149b894dc8d053ae96ac45bd913c0a52c8782063f593ba6eab24a00f4ffb30122ba17bc3f3",
    "0x845f856a865ceed3d409c181dd70d2a5eb519eab10e2685cb8c87776b87ad81c51e63a56f3dbe4fc24b8b47cc1d46225",
    "0xb341d67fac0c4e9761d13fae297ff4ee8c79bc1cf9d9fbe827ed22308f28c595467e3cdb035630d486b000f7a2d016b2"
   ],
   "builder_registration": {
    "message": {
     "fee_recipient": "0x86b8145c98e5bd25ba722645b15ed65f024a87ec",
     "gas_limit": 36000000,
     "timestamp": 1606824023,
     "pubkey": "0x92360c8ab886fb5188e58091932b08a8dbc17c1fd3510c0e52816478d4ede55d352bdf6f5e165ee2382d7d73ab6b330b"
    },
    "signature": "0xaa0a40ee7e8ff66c5b0127d601fa3167d0af8038064dce985b18e0724918c08dccc872111b87e8f9cfaf6ddcaea0a69202823e8299ba90c134cf67fc410e9470200a683d77843c471d25cb263acb85aedcc36c4ed6041f66459a91aaa6d8d8c8"
   },
   "partial_deposit_data": [
    {
     "pubkey": "0x92360c8ab886fb5188e58091932b08a8dbc17c1fd3510c0e52816478d4ede55d352bdf6f5e165ee2382d7d73ab6b330b",
     "withdrawal_credentials": "0x02000000000000000000000086b8145c98e5bd25ba722645b15ed65f024a87ec",
     "amount": "1000000000",
     "signature": "0xa376cad5d7a52be801524b8215aa1c1606ed67c91f1867149e84255c7d8a09a4162bd7c77893de36eacc0bc0bf1c461303f4971b00b1f8ca0ee3d37d913f5363e79975c7a0d0d6f31a7e4bc6dafe53e6549e6006d6e378d21f27e3ca298ac634"
    },
    {
     "pubkey": "0x92360c8ab886fb5188e58091932b08a8dbc17c1fd3510c0e52816478d4ede55d352bdf6f5e165ee2382d7d73ab6b330b",
     "withdrawal_credentials": "0x02000000000000000000000086b8145c98e5bd25ba722645b15ed65f024a87ec",
     "amount": "8000000000",
     "signature": "0xb5c0d0934ac829f427d7afdc237d35fe296574baa7ab499f4dae4f3290012565b246d0baa303f8b843226a3f887497f80f2f50ff2a9e9c93fa13f76e7b36be930d4df17fcebdc323db422a360805b160687c841cf13572ca2dc1f5247bc953c5"
    },
    {
     "pubkey": "0x92360c8ab886fb5188e58091932b08a8dbc17c1fd3510c0e52816478d4ede55d352bdf6f5e165ee2382d7d73ab6b330b",
     "withdrawal_credentials": "0x02000000000000000000000086b8145c98e5bd25ba722645b15ed65f024a87ec",
     "amount": "32000000000",
     "signature": "0x876823015c445b40c9c8a787235cd5f8f7b97967e8548b9d8df013409c1748fa247d4a298b7a06b28e54eeabb367dad306b6f34588321467da1dc6619f720c4de2777999d68d8bfec0666a07e31f36b6320297658eae08287691dcc87d62ced5"
    },
    {
     "pubkey": "0x92360c8ab886fb5188e58091932b08a8dbc17c1fd3510c0e52816478d4ede55d352bdf6f5e165ee2382d7d73ab6b330b",
     "withdrawal_credentials": "0x02000000000000000000000086b8145c98e5bd25ba722645b15ed65f024a87ec",
     "amount": "256000000000",
     "signature": "0x957e30cb82c704d4c232dd5793b8b3e8747137344412d2f9b25a3584e796089b2c5af04327c45512febafe9a44cc42c6166644e37f93443b7e6d4c3c4a621003db32ef48142c267b1de161e34b0fdbfc2e4d9e8ccde4362e6583bea987877648"
    }
   ]
  }
 ],
 "signature_aggregate": "0x81c3637eed59db687012f907a8fe5b99f072cabd86ef54af2f213eb42b485ee522aa6f6948e14bf72607ac1fdc3d71440431e7e38cd22cf74f3b56e5caa2e99b4fe2c7eda993c74b59be0d419b62e31e3ea823949164d6c627a7fd7080dc19bf",
 "lock_hash": "0xabff2cc9e569c815a27807bfe460e5a46e49df654ff04edde06efa338a011c74",
 "node_signatures": [
